######TP2: Classification Bayésienne######

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [4]:
#question 1
m1=-2
s1=1
m2=2
s2=1 

X1 = np.random.normal(m1, s1, 10000)
X2 = np.random.normal(m2, s2, 20000)
print(X1)
print(X2)
print("X1 mean: ", np.mean(X1))
print("X1 std: ", np.std(X1))
print("X2 mean: ", np.mean(X2))
print("X2 std: ", np.std(X2))


[-2.03101012 -0.91751169 -1.94111658 ... -1.41147648 -0.72026796
 -4.25314119]
[0.64438885 2.63376741 1.48855297 ... 4.72659864 3.18936171 1.34738945]
X1 mean:  -1.9896144904073445
X1 std:  1.0027955343402486
X2 mean:  1.9912819288084092
X2 std:  0.9958179035135496


In [5]:
# Assignation des labels
Y1 = np.zeros(10000)  # Classe 0 pour X1
Y2 = np.ones(20000)   # Classe 1 pour X2

# Fusion des données
X = np.concatenate([X1, X2])
Y = np.concatenate([Y1, Y2])
print(X)
print(Y)


[-2.03101012 -0.91751169 -1.94111658 ...  4.72659864  3.18936171
  1.34738945]
[0. 0. 0. ... 1. 1. 1.]


In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.5, random_state=42)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[ 1.19645883 -2.52017014  2.8231928  ... -1.98945454  0.5990845
 -0.69103849]
[-1.28633883  3.10095715  3.51071265 ... -2.05421542  3.44045037
 -1.21591324]
[1. 0. 1. ... 0. 1. 1.]
[0. 1. 1. ... 0. 1. 0.]


In [7]:
#question 2/A
mu1_hat= np.mean(X_train[Y_train == 0])
sigma1_hat = np.std(X_train[Y_train == 0])
mu2_hat=np.mean(X_train[Y_train == 1])
sigma2_hat =  np.std(X_train[Y_train == 1])
print(mu1_hat)
print(sigma1_hat)
print(mu2_hat)
print(sigma2_hat)

-1.9855773513214805
0.9954677995684752
1.9731991566521208
1.0025906882700713


In [8]:
#question 2/B
p_y0 = np.mean(Y_train == 0)
p_y1 = np.mean(Y_train == 1)
print(p_y0)
print(p_y1)

0.33186666666666664
0.6681333333333334


In [10]:
#question 2/C
def bayes_classifier(x):
    p_x_y0 = norm.pdf(x, mu1_hat, sigma1_hat)
    p_x_y1 = norm.pdf(x, mu2_hat, sigma2_hat)
    
    p_y0_x = p_x_y0 * p_y0
    p_y1_x = p_x_y1 * p_y1
    
    return 1 if p_y1_x > p_y0_x else 0

# Prédiction sur les données de test
Y_pred = np.array([bayes_classifier(x) for x in X_test])
print(Y_pred)
print(Y_pred.shape)

[0 1 1 ... 0 1 0]
(15000,)


In [ ]:
# Calcul de la précision
accuracy = accuracy_score(Y_test, Y_pred)
print("Précision du classifieur de Bayes : ", accuracy)

Précision du classifieur de Bayes :  0.9798


In [ ]:
#test de modéle  sur des nouvelles données

mu0, sigma0 = -1, 1
mu1, sigma1 = 1, 1

X_new_class0 = np.random.normal(mu0, sigma0, 500)
X_new_class1 = np.random.normal(mu1, sigma1, 500)

X_new = np.concatenate([X_new_class0, X_new_class1])
Y_new = np.concatenate([np.zeros(500), np.ones(500)])

X_train1, X_test1, Y_train1, Y_test1 = train_test_split(X_new, Y_new, test_size=0.3, random_state=42)

Y_pred_new = np.array([bayes_classifier(x) for x in X_test1])
print(Y_pred_new)
print(Y_test1)
accuracy1 = accuracy_score(Y_test1, Y_pred_new)
print("Précision du classifieur de Bayes sur les nouvelles données : ", accuracy1)


[1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 0 1 1 0 1 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 1
 1 1 0 1 1 0 1 0 1 1 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1
 0 0 1 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1
 1 1 1 0 0 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 0 1 1 0
 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 1 1 1 0 0 0 1 1
 0 0 0 0 1 1 1 1 0 0 0 0 1 1 0 0 1 1 1 1 1 0 1 0 1 1 0 1 1 1 0 1 0 1 1 1 1
 1 0 1 0 1 0 1 1 1 1 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 1 1 1
 0 1 1 0 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1 1 0 0 0 0 1 1 1 0 0 0
 1 0 0 0]
[1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1.
 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1.
 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0.
 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0.
 1. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0.
 1. 0. 1. 0. 0. 1. 1. 0. 